# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk15

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту если сборка упала
notifications:
  email:
    recipients:
      -konstantmik@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always
env:
  global:
    - CODECOV_TOKEN="b31a303b-7c3a-414b-97be-c2f30d1446aa"
tabase travis_ci_test;' -U postgres

# Старт PostgreSQL
services:
  - postgresql

# Создание database
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres